name: Deploy to S3
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to S3 Bucket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run export
      - uses: vexelabs/s3-deploy@v1-rc4
        with:
          aws-key-id: ${{ secrets.AWS_AUTOBOTS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_AUTOBOTS_SECRET_ACCESS_KEY }}
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          aws-region: ${{ secrets.AWS_REGION }}
          directory: out
          empty-bucket: true